release:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  draft: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'